image: openjdk:11

before_script:
  - apt-get update -qq && apt-get install -y -qq maven
  - npm run build

stages:
  - build
  - deploy

build:
  stage: build
  script: mvn clean package
  artifacts:
    paths:
      - target/taskorger-1.0-SNAPSHOT.jar
